myblog/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('owner', views.owner, name='owner'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

myblog/blog/models.py
from django.db import models
from datetime import datetime


class Owner(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Comment(models.Model):
    date = models.DateTimeField()
    author= models.CharField(max_length=200)
    text =  models.TextField(default="")

    def __str__(self):
        return self.text

class Post(models.Model):
    id= models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    date = models.DateTimeField()
    author= models.ForeignKey(Owner, on_delete=models.CASCADE)
    text= models.TextField(default="")
    comments= models.ManyToManyField(Comment)

    def __str__(self):
        return self.title

myblog/myblog/forms.py
from django import forms
from blog.models import *


class CommentForm(forms.ModelForm):
        class Meta:
            model = Comment
            exclude = ('date', )
            widgets = {
            'post_Id': forms.NumberInput(attrs={
                'required': True,
                'placeholder': '0'
            }),
        }


        # def __init__(self, *args, **kwargs):
        #     super(CommentForm, self).__init__(*args, **kwargs)
        #     self.fields['description'].widget = TextInput(attrs={
        #         'id': 'myCustomId',
        #         'class': 'myCustomClass',
        #         'name': 'myCustomName',
        #         'placeholder': 'myCustomPlaceholder'})

myblog/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from myblog.forms import *
from .models import *
from datetime import datetime

# Create your views here.
def index(request):
    if request.method == "POST":
        #print('this is a post')
        form = CommentForm(request.POST)
        #if form.is_valid():
            # comment = form.save(commit=False)
            # comment.author = form.cleaned_data['author']
            # comment.text= form.cleaned_data['text']
            # comment.date = datetime.now()

            # comment = form.save(commit=False)
        author = request.POST['author']
        text= request.POST['text']
        postId= request.POST['post_Id']
        date = datetime.now()
        comment = Comment.objects.create(author=author, text=text, date= date)
        #print(comment)


            #comment.save()

            #postId= request.POST.get('id', 2)
            #print(postId)
        curr_post= Post.objects.get(id= postId)
        #print(curr_post)
        curr_post.comments.add(comment)
        #print(curr_post.comments)
        curr_post.save()
        return redirect('/blog/')
    else:
        form= CommentForm()

    posts= Post.objects.all()
    context={'blog_posts': posts, 'form': form}
    return render(request, "blog_page.html", context)

def owner(request):
    if request.method == "POST":
        #print('this is a post')
        form = CommentForm(request.POST)
        #if form.is_valid():
            # comment = form.save(commit=False)
            # comment.author = form.cleaned_data['author']
            # comment.text= form.cleaned_data['text']
            # comment.date = datetime.now()

            # comment = form.save(commit=False)
        author = request.POST['author']
        text= request.POST['text']
        postId= request.POST['post_Id']
        date = datetime.now()
        comment = Comment.objects.create(author=author, text=text, date= date)
        #print(comment)


            #comment.save()

            #postId= request.POST.get('id', 2)
            #print(postId)
        curr_post= Post.objects.get(id= postId)
        #print(curr_post)
        curr_post.comments.add(comment)
        #print(curr_post.comments)
        curr_post.save()
        return redirect('/blog/owner')
    else:
        form= CommentForm()

    posts= Post.objects.all()
    context={'blog_posts': posts, 'form': form}
    return render(request, "blog_owner.html", context)

myblog/myblog/templates/blog_owner.html
{% extends 'blog_page.html' %}
{% block content %}

<button style="display:inline-block; float: left;" class= "btn btn-success m-3 " type="button">New Post</button>

{% endblock %}

myblog/myblog/templates/blog_page.html
<!DOCTYPE html>
<html>

<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-latest.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <title>My Blog</title>

  <style>
    div {display:inline-block;}
    li {list-style-type: none;}
    h2{text-decoration: underline;}
    .jumbotron{margin-bottom:0px;}
    .close_form {float: right; padding: 3px;}
    .ic{display: inline-block; vertical-align: top;}
    .comm_detail{display: inline-block;}
    .add_comm {display: block; margin-bottom:10%;}
    .comm{display: block; margin:5%; width:150px;}
    .comm_detail{display:inline;}
    .nav-item{float: left;}
    .recent{float:right; margin-right:5%;}
    .posts{margin-left: 5%; margin-bottom:5%;}
    .text{margin-top: 10px;}

  </style>

</head>

<body>
  <div class="jumbotron jumbotron-fluid col-sm-12">
    <div class="container">
      <h1 class="display-4">My Blog</h1>
    </div>
  </div>

  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand nav-item nav-link mr-auto" href="#">Home</a>
  </nav>


  <div class="col-xs-12 col-sm-8 posts border ">
    <ul>
      <li >
        {% for post in blog_posts %}
        <h2 id="post_{{post.id}}">{{ post.title}}</h2>
          <small class="text-muted"> By {{ post.author}} on {{ post.date }} </small>
          <p class="text">{{ post.text }} </p>
          <div class="m-3" id= "comments_{{post.id}}">
            <h4>Comments:</h4>
            {% for comment in post.comments.all %}
            <div class= "comm">
              <span class="ic"><i class="material-icons account_icon">account_circle</i></span>
              <span class="comm_detail"><b>{{comment.author}}</b></span><br/>
              <span>  {{comment.text}}</span> <br/>
              <small class="text-muted">{{comment.date}}</small> <br/>
            </div>
            {% endfor %}
          </div>

      <button class= "btn btn-primary m-3 add_comm " type="button" id= "new_comm_{{post.id}}" onclick="showForm({{post.id}})">Add Comment</button>

      <form action="" style="visibility: hidden; display: none;" id={{post.id}}>
        <div class="form-group">
          {% csrf_token %}
          <p><label for="id_author">Name:</label> <input class= form-control type="text" name="author" maxlength="200" required="" id="id_author_{{post.id}}" /></p>
          <p><label for="id_text">Comment:</label> <textarea class= form-control name="text" cols="40" rows="10" required="" id="id_text_{{post.id}}"></textarea></p>
          <div style= "visibility: hidden; display: none;" class="alert alert-danger" id="form_alert_{{post.id}}" role="alert">
          </div>
          <button class="sub btn btn-primary" type="button" >Post Comment</button>
          <a href='' class='close_form'><i class="material-icons" onclick="hideForm({{post.id}});return false;">close</i></a>
        </div>
      </form>
      {% endfor %}
    </li>
  </ul>
</div>


  <div class="recent col-sm-2 hidden-xs border">
    <h3>Recent Posts</h3><br/>
    <nav class="nav flex-column">
       {% for post in blog_posts|slice:"5" %}
       <a href='#post_{{post.id}}'>{{ post.title }}</a><br/>
      {% endfor %}
    </nav>
  </div>

<!-- <div class= "col-sm-1">
  {% block content %}
  {% endblock %}
</div> -->

{% block javascript %}
<script>
function showForm(id){
  $("#new_comm_" + id ).attr('style','visibility: hidden; display: none;');
  $("#" +id ).attr('style','visibility: visible; display: block;');
};
function hideForm(id){
  $("#new_comm_" + id ).attr('style','visibility: visible; display: block;');
  $("#" + id ).attr('style','visibility: hidden; display: none;');
};

$('.sub').on('click', function(event){
  event.preventDefault();
  console.log("submitted!")
  var post_Id= $(this).closest("form").attr('id');
  var author = $("#id_author_" +  + post_Id).val();
  var text = $("#id_text_" + post_Id).val();
  console.log(post_Id);
  if(author == '' || text == ''){
    $("#form_alert_" +  + post_Id).attr('style','visibility: visible; display: block;');
    $("#form_alert_" +  + post_Id).text("Please fill out all fields!");
  }
  else{
    add_comment(post_Id, author, text);
  }
  event.stopImmediatePropagation();
  });



function add_comment(id, author, text) {
console.log("create post is working!")
$.ajax({
    url : "/blog/",
    type : "POST",
    data : { post_Id : id,
            author : author,
            text : text,
            csrfmiddlewaretoken: '{{ csrf_token }}'
    },
    success : function(json) {
        var today= new Date();
        var months= ["Jan.", "Feb.", "Mar.", "Apr.", "May", "Jun.", "Jul.", "Aug.", "Sep.", "Oct.", "Nov.", "Dec."];
        var hours= today.getHours();
        var mins= ('0'+today.getMinutes()).slice(-2);
        var meridiem= "a.m.";
        if (hours > 12){
          hours= hours -12;
          meridiem= "p.m."
        }
        var date= (months[today.getMonth()]) + ' ' + (today.getDate()) + ', ' + today.getFullYear() + ', '+ hours +':' + mins + " " + meridiem;
        hideForm(id);
        $('#comments_' + id).append(
          `<div class= "comm">
           <span class="ic"><i class="material-icons account_icon">account_circle</i></span>
          <span class="comm_detail"><b>` + author + `</b><br/>` +
           text + `<br/>
           <small class="text-muted">`+ date +`</small> <br/></span>
          </div>`
        );
        console.log("success");
    },
    error : function(xhr,errmsg,err) {
        console.log(err);
    }
});
};
</script>
{% endblock javascript %}

<!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>

</html>